sudo: false

language: c
os: linux

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

env:
  - CHOOSENIM_CHOOSE_VERSION="devel"

install:
  - git clone https://github.com/nsf/termbox
  - cd termbox
  - ./waf configure --prefix=/usr
  - ./waf
  - sudo ./waf install --destdir=PREFIX
  - cd ..
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y

before_script:
  - set -e

script:
  - nimble install -y
